export const GET_RABBITS_START = 'GET_RABBITS_START';
export const GET_RABBITS_SUCCESS = 'GET_RABBITS_SUCCESS';
export const GET_RABBITS_FAIL = 'GET_RABBITS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_RABBIT_START = 'ADD_RABBIT_START';
export const ADD_RABBIT_SUCCESS = 'ADD_RABBIT_SUCCESS';
export const ADD_RABBIT_FAIL = 'ADD_RABBIT_FAIL';
export const RABBIT_DATA_SENT = 'RABBIT_DATA_SENT';

export const DELETE_RABBIT = 'DELETE_RABBIT';

export const UPDATE_RABBIT = 'UPDATE_RABBIT';
